behaviors:
  Hummingbird_Conservative:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 2000000
    time_horizon: 64
    summary_freq: 10000

  Hummingbird_Aggressive:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 2000000
    time_horizon: 64
    summary_freq: 10000

# --- NEW CURRICULUM SECTION ---
environment_parameters:
  lesson:
    curriculum:
      - name: Lesson0_Easy         # Start with an easy environment
        completion_criteria:
          measure: reward
          behavior: Hummingbird_Aggressive # We'll use the faster learner to advance
          signal_smoothing: true
          min_lesson_length: 100
          threshold: -0.25         # Advance when avg reward is better than -0.25
        value: 0.0               # Corresponds to lesson 0 in C#

      - name: Lesson1_Medium        # Move to a medium environment
        completion_criteria:
          measure: reward
          behavior: Hummingbird_Aggressive
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.2           # Advance when avg reward is positive
        value: 0.5               # Corresponds to lesson 0.5 in C#

      - name: Lesson2_Hard          # The final, target environment
        value: 1.0               # Corresponds to lesson 1.0 in C#